"""Changed some colums from nullable=false to true state.

Revision ID: 7afb9ba6a71c
Revises: b76d8ff88df2
Create Date: 2026-08-09 17:09:51.515240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afb9ba6a71c'
down_revision: Union[str, Sequence[str], None] = 'b76d8ff88df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'faculty_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'course',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'course',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'faculty_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
