"""Privacy setting for posts and users

Revision ID: ac8857a76f3a
Revises: 18b7b1ee2a24
Create Date: 2026-08-06 17:19:26.861029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8857a76f3a'
down_revision: Union[str, Sequence[str], None] = '18b7b1ee2a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    op.drop_column('posts', 'is_active')
    # ### end Alembic commands ###
