"""Privacy setting for posts and users

Revision ID: b76d8ff88df2
Revises: 18b7b1ee2a24
Create Date: 2026-08-06 18:05:12.674348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76d8ff88df2'
down_revision: Union[str, Sequence[str], None] = '18b7b1ee2a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_privacy_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('to_everyone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('to_faculty', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('to_group', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('to_course', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('post_privacy_settings',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('to_everyone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('to_faculty', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('to_group', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('to_course', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.add_column('posts', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    op.drop_column('posts', 'is_active')
    op.drop_table('post_privacy_settings')
    op.drop_table('user_privacy_settings')
    # ### end Alembic commands ###
